WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		CLINICAL_EVENT,
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE
	WHERE
		CLINICAL_EVENT.EVENT_CD = 926562948 -- prothrombin complex
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN DATE '2015-09-01' AND DATE '2019-04-21'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		AND CLINICAL_EVENT.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^I61|^I62') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 641836527 -- ICD-10-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome

	UNION

	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID
	FROM
		CLINICAL_EVENT,
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE
	WHERE
		CLINICAL_EVENT.EVENT_CD = 926562948 -- prothrombin complex
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN DATE '2013-05-01' AND DATE '2015-11-01'
		AND CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.LOC_FACILITY_CD = 3310 -- HH HERMANN
		AND CLINICAL_EVENT.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
		AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
		AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '^431|^432.9') > 0
		AND NOMENCLATURE.SOURCE_VOCABULARY_CD = 739 -- ICD-9-CM
		AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
)

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN
FROM
	ENCNTR_ALIAS,
	ORDERS,
	PATIENTS
WHERE
	PATIENTS.PERSON_ID = ORDERS.PERSON_ID
	AND PATIENTS.ENCNTR_ID = ORDERS.ENCNTR_ID
	AND ORDERS.CATALOG_CD IN (
		9902731, -- warfarin
		642177882, -- rivaroxaban
		894197557, -- apixaban
		1466817855 -- edoxaban
	) 
	AND ORDERS.CATALOG_TYPE_CD = 1363 -- Pharmacy
	AND ORDERS.ACTIVITY_TYPE_CD = 378 -- Pharmacy
	AND ORDERS.ORIG_ORD_AS_FLAG = 2 -- Recorded / Home Meds
	AND PATIENTS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
