SELECT DISTINCT
	ENCOUNTER.ENCNTR_ID AS ENCOUNTER_ID,
	pi_from_gmt(CE_INR.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS EVENT_DATETIME,
	CE_INR.RESULT_VAL AS RESULT,
	CASE CV_INR.CDF_MEANING
		WHEN 'NUM' THEN
			CASE NVL(LENGTH(TRIM(CE_INR.RESULT_VAL)), 99999)
				WHEN 99999 THEN 0
				ELSE 
					CASE NVL(LENGTH(TRIM(TRANSLATE(TRIM(CE_INR.RESULT_VAL), '. 0123456789', ' '))), 0)
						WHEN 0 THEN TO_NUMBER(CE_INR.RESULT_VAL)
						ELSE 0
					END
			END
		ELSE 0
	END AS NUM_RESULT
FROM
	CLINICAL_EVENT,
	CLINICAL_EVENT CE_INR,
	CODE_VALUE CV_INR,
    DIAGNOSIS,
	ENCNTR_ALIAS,
	ENCOUNTER,
	NOMENCLATURE
WHERE
	CLINICAL_EVENT.EVENT_CD = 926562948 -- prothrombin complex
	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN DATE '2015-09-01' AND DATE '2019-07-01'
	AND (
		CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.ACTIVE_IND = 1
		AND ENCOUNTER.LOC_FACILITY_CD IN (3310, 3796) -- HH HERMANN, HC Childrens
	)
	AND (
		ENCOUNTER.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.END_EFFECTIVE_DT_TM > SYSDATE
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	)
	AND (
	    CLINICAL_EVENT.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
        AND DIAGNOSIS.ACTIVE_IND = 1
        AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
	)
    AND (
        DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
        AND NOMENCLATURE.ACTIVE_IND = 1
        AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, 'I61|I62') > 0
    )
    AND (
        CLINICAL_EVENT.ENCNTR_ID = CE_INR.ENCNTR_ID(+)
        AND CE_INR.EVENT_CD(+) = 32089
		AND CE_INR.EVENT_CD = CV_INR.CODE_VALUE(+)
    )

UNION

SELECT DISTINCT
	ENCOUNTER.ENCNTR_ID AS ENCOUNTER_ID,
	ENCNTR_ALIAS.ALIAS AS FIN,
	MAX(CE_INR.RESULT_VAL) KEEP (DENSE_RANK FIRST ORDER BY CE_INR.EVENT_END_DT_TM) AS INR_MAX
FROM
	CLINICAL_EVENT,
	CLINICAL_EVENT CE_INR,
    DIAGNOSIS,
	ENCNTR_ALIAS,
	ENCOUNTER,
	NOMENCLATURE
WHERE
	CLINICAL_EVENT.EVENT_CD = 926562948 -- prothrombin complex
	AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
	AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN DATE '2015-09-01' AND DATE '2019-07-01'
	AND (
		CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCOUNTER.ACTIVE_IND = 1
		AND ENCOUNTER.LOC_FACILITY_CD IN (3310, 3796) -- HH HERMANN, HC Childrens
	)
	AND (
		ENCOUNTER.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.END_EFFECTIVE_DT_TM > SYSDATE
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
	)
	AND (
	    CLINICAL_EVENT.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
        AND DIAGNOSIS.ACTIVE_IND = 1
        AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
	)
    AND (
        DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
        AND NOMENCLATURE.ACTIVE_IND = 1
        AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, 'I61|I62') > 0
    )
    AND (
        CLINICAL_EVENT.ENCNTR_ID = CE_INR.ENCNTR_ID(+)
        AND CE_INR.EVENT_CD(+) = 32089
    )
GROUP BY
    ENCOUNTER.ENCNTR_ID,
	ENCNTR_ALIAS.ALIAS
