WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.DISCH_DT_TM
	FROM
		CLINICAL_EVENT,
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE
	WHERE
		CLINICAL_EVENT.EVENT_CD = 926562948 -- prothrombin complex
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN DATE '2015-09-01' AND DATE '2019-07-01'
		AND (
			CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
			AND ENCOUNTER.ACTIVE_IND = 1
			AND ENCOUNTER.LOC_FACILITY_CD IN (3310, 3796) -- HH HERMANN, HC Childrens
		)
		AND (
			CLINICAL_EVENT.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
			AND DIAGNOSIS.ACTIVE_IND = 1
			AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		)
		AND (
			DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
			AND NOMENCLATURE.ACTIVE_IND = 1
			AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, 'I61|I62') > 0
		)

	UNION

	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.DISCH_DT_TM
	FROM
		CLINICAL_EVENT,
		DIAGNOSIS,
		ENCOUNTER,
		NOMENCLATURE
	WHERE
		CLINICAL_EVENT.EVENT_CD = 926562948 -- prothrombin complex
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31' 
		AND CLINICAL_EVENT.EVENT_END_DT_TM BETWEEN DATE '2013-05-01' AND DATE '2015-11-01'
		AND (
			CLINICAL_EVENT.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
			AND ENCOUNTER.ACTIVE_IND = 1
			AND ENCOUNTER.LOC_FACILITY_CD IN (3310, 3796) -- HH HERMANN, HC Childrens
		)
		AND (
			CLINICAL_EVENT.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
			AND DIAGNOSIS.ACTIVE_IND = 1
			AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
		)
		AND (
			DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
			AND NOMENCLATURE.ACTIVE_IND = 1
			AND REGEXP_INSTR(NOMENCLATURE.SOURCE_IDENTIFIER, '431|432.9') > 0
		)
), UNIT_IN_OUT AS (
	SELECT DISTINCT
		ENCNTR_LOC_HIST.ENCNTR_ID,
		ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD,
		ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM,
		LEAST(ENCNTR_LOC_HIST.END_EFFECTIVE_DT_TM, PATIENTS.DISCH_DT_TM) - ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM AS TRANSACTION_DURATION,
		CASE
			WHEN 
				LAG(ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD, 1, 0) OVER (
					PARTITION BY ENCNTR_LOC_HIST.ENCNTR_ID 
					ORDER BY ENCNTR_LOC_HIST.ENCNTR_LOC_HIST_ID
				) <> ENCNTR_LOC_HIST.LOC_NURSE_UNIT_CD THEN 1
			ELSE 0
		END AS UNIT_IN
	FROM
		ENCNTR_LOC_HIST,
		PATIENTS
	WHERE
		PATIENTS.ENCNTR_ID = ENCNTR_LOC_HIST.ENCNTR_ID
		AND PATIENTS.DISCH_DT_TM >= ENCNTR_LOC_HIST.BEG_EFFECTIVE_DT_TM
), UNIT_COUNT AS (
	SELECT DISTINCT
		UNIT_IN_OUT.ENCNTR_ID,
		UNIT_IN_OUT.LOC_NURSE_UNIT_CD,
		SUM(UNIT_IN_OUT.UNIT_IN) OVER (PARTITION BY UNIT_IN_OUT.ENCNTR_ID ORDER BY UNIT_IN_OUT.BEG_EFFECTIVE_DT_TM) AS UNIT_COUNT,
		UNIT_IN_OUT.TRANSACTION_DURATION
	FROM
		UNIT_IN_OUT
), UNIT_LOS AS (
	SELECT
		UNIT_COUNT.ENCNTR_ID,
		UNIT_COUNT.UNIT_COUNT,
		UNIT_COUNT.LOC_NURSE_UNIT_CD,
		SUM(UNIT_COUNT.TRANSACTION_DURATION) AS UNIT_LOS
	FROM
		UNIT_COUNT
	WHERE
		UNIT_COUNT.LOC_NURSE_UNIT_CD IN (
			5441, -- HH STIC
			27226894, -- HH TSIC
			283905037 -- HH 7J
		)
	GROUP BY
		UNIT_COUNT.ENCNTR_ID,
		UNIT_COUNT.UNIT_COUNT,
		UNIT_COUNT.LOC_NURSE_UNIT_CD
)

SELECT
	ENCNTR_ALIAS.ALIAS AS FIN,
	pi_get_cv_display(UNIT_LOS.LOC_NURSE_UNIT_CD) AS NURSE_UNIT,
	MAX(UNIT_LOS.UNIT_LOS) KEEP (DENSE_RANK FIRST ORDER BY UNIT_LOS.UNIT_COUNT) AS UNIT_LOS
FROM
	ENCNTR_ALIAS,
	UNIT_LOS
WHERE
	UNIT_LOS.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
	AND ENCNTR_ALIAS.ACTIVE_IND = 1
	AND ENCNTR_ALIAS.END_EFFECTIVE_DT_TM > SYSDATE
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
GROUP BY
	ENCNTR_ALIAS.ALIAS,
	UNIT_LOS.LOC_NURSE_UNIT_CD
	