WITH PATIENTS AS (
	SELECT DISTINCT
		ENCOUNTER.ENCNTR_ID,
		ENCOUNTER.PERSON_ID,
		ENCNTR_ALIAS.ALIAS,
		ENCOUNTER.DISCH_DT_TM
	FROM
		ENCNTR_ALIAS,
		ENCOUNTER
	WHERE
	    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_ALIAS.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
)

SELECT DISTINCT
	PATIENTS.ALIAS AS FIN,
	pi_get_cv_display(NOMENCLATURE.SOURCE_VOCABULARY_CD) AS ICD_TYPE,
	NOMENCLATURE.SOURCE_IDENTIFIER AS ICD_CODE,
	NOMENCLATURE.SOURCE_STRING AS ICD_DESCRIPTION,
	DIAGNOSIS.DIAG_PRIORITY AS CODE_PRIORITY
FROM
	DIAGNOSIS,
	NOMENCLATURE,
	PATIENTS
WHERE
    PATIENTS.ENCNTR_ID = DIAGNOSIS.ENCNTR_ID
	AND DIAGNOSIS.DIAG_TYPE_CD = 26244 -- Final
	AND DIAGNOSIS.NOMENCLATURE_ID = NOMENCLATURE.NOMENCLATURE_ID
	AND NOMENCLATURE.SOURCE_VOCABULARY_CD IN (
		739, -- ICD-9-CM
		641836527 -- ICD-10-CM
	)
	AND NOMENCLATURE.PRINCIPLE_TYPE_CD = 751 -- Disease or Syndrome
	